# Generated by Django 5.1.1 on 2025-04-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='postion',
            new_name='position',
        ),
    ]
